-- Intentionally a no-op (MUL-5400).
--
-- The original migration reclassified historical skill-bundle download
-- failures in agent_task_queue and chat_message. Production has about 4 million
-- task rows, while fewer than 2,000 match the legacy failure shape, so applying
-- the backfill during deployment would require a disproportionate full-table
-- scan for an observability-only correction.
--
-- MUL-5370's runtime behavior does not depend on this backfill: current daemons
-- emit skill_bundle_unavailable directly, and the server normalizes the exact
-- legacy daemon error before deciding whether to retry. Historical rows may
-- therefore remain agent_error.unknown without affecting new task retries or
-- user-facing errors.
--
-- Keep the migration version so databases that already applied the original
-- development migration and production databases that have not applied it can
-- continue through the same version sequence. The migration runner tracks the
-- filename rather than a content checksum.
SELECT 1;
