import { describe, expect, it } from "vitest";
import { InboxListSchema } from "./schemas";
// Emitted by TestWriteLegacyProjectionGolden in
// server/internal/service/inboxv2. Imported rather than duplicated so this test
// fails when the Go projection changes shape.
import legacyProjectionGolden from "../../../server/internal/service/inboxv2/testdata/legacy_projection.json";

/**
 * Tests for mobile's CLIENT-SIDE parsing of GET /api/inbox.
 *
 * Scope, stated precisely because the name of this file used to overclaim:
 * these are hand-written fixtures run against `InboxListSchema`. They pin how
 * this client REACTS to a given payload. They cannot fail when the Go server
 * starts sending something new — nothing here executes server code.
 *
 * The matching server-side guarantee used to be described as structural —
 * "every `details` map in notification_listeners.go is typed
 * `map[string]string`". That only ever covered ONE of the producers:
 * autopilot_failure_monitor.go and task.go both build `map[string]any`, and
 * the pause monitor puts real numbers in (failed_runs, total_runs, fail_pct,
 * lookback_seconds, threshold_*). So the invariant this file documents has been
 * violated in production code the whole time.
 *
 * The inbox v2 projection closes it for real: every legacy row is rendered from
 * inboxv2.LegacyPayload, whose Details field is `map[string]string`, and every
 * producer's map goes through inboxv2.StringDetails. The golden file parsed
 * below is emitted by that projection, so a regression on the Go side fails
 * here rather than in someone's inbox.
 *
 * Why both halves exist: during MUL-5483 a new inbox type was added and the
 * mobile label map was updated so `tsc` passed — but a NUMBER went into
 * `details.child_count`, and `details` is `z.record(z.string(), z.string())`.
 * Because the endpoint parses an ARRAY, one bad row fails the whole parse and
 * `listInbox` falls back to `EMPTY_INBOX_LIST`: the entire mobile inbox
 * renders empty, not just that row. The blast radius is what these tests
 * document; the compile-time type is what prevents it.
 */
describe("inbox list schema", () => {
  it("parses a row shaped like the documented server payload", () => {
    const serverRow = {
      id: "inbox-1",
      workspace_id: "ws-1",
      recipient_type: "member",
      recipient_id: "user-1",
      type: "status_changed",
      severity: "info",
      issue_id: "issue-1",
      title: "P0: delegated subscription rule",
      body: "",
      actor_type: "agent",
      actor_id: "agent-1",
      read: false,
      archived: false,
      created_at: "2026-07-30T00:00:00Z",
      // Every value is a string. A number here drops the whole list.
      details: { from: "in_progress", to: "in_review" },
    };

    const parsed = InboxListSchema.safeParse([serverRow]);
    expect(parsed.success).toBe(true);
    expect(parsed.success && parsed.data[0]?.type).toBe("status_changed");
    expect(parsed.success && parsed.data[0]?.details?.to).toBe("in_review");
  });

  it("rejects a numeric details value", () => {
    const badRow = {
      id: "inbox-2",
      recipient_type: "member",
      type: "status_changed",
      details: { child_count: 3 },
    };

    expect(InboxListSchema.safeParse([badRow]).success).toBe(false);
  });

  it("keeps one malformed row from emptying the entire list observable", () => {
    // Documents the blast radius that made this a P1 rather than a cosmetic bug:
    // the schema is an array, so a single bad row invalidates every good one.
    const good = {
      id: "inbox-3",
      recipient_type: "member",
      type: "status_changed",
      details: { from: "todo", to: "in_review" },
    };
    const bad = {
      id: "inbox-4",
      recipient_type: "member",
      type: "status_changed",
      details: { child_count: 3 },
    };

    expect(InboxListSchema.safeParse([good]).success).toBe(true);
    expect(InboxListSchema.safeParse([good, bad]).success).toBe(false);
  });

  // The contract test §8 asks for: the server's projection output, parsed by the
  // real client schema. Unlike the fixtures above, this one is generated by
  // TestWriteLegacyProjectionGolden in the Go package, so it fails when the
  // server drifts — which is the whole reason it exists.
  it("parses the server's legacy projection golden", () => {
    const parsed = InboxListSchema.safeParse(legacyProjectionGolden);
    if (!parsed.success) {
      throw new Error(
        `the inbox v2 legacy projection no longer parses: ${JSON.stringify(parsed.error.issues, null, 2)}`,
      );
    }
    expect(parsed.data.length).toBe(legacyProjectionGolden.length);

    // The row that used to carry numbers. Every value must now be a string.
    const paused = parsed.data.find((r) => r.type === "autopilot_paused");
    expect(paused).toBeDefined();
    for (const [key, value] of Object.entries(paused?.details ?? {})) {
      expect(typeof value, `details.${key}`).toBe("string");
    }

    // read/archived must survive the projection as booleans the list relies on.
    expect(parsed.data.some((r) => r.archived === true)).toBe(true);
    expect(parsed.data.some((r) => r.read === false)).toBe(true);
  });

  it("renders an unknown server type instead of dropping the row", () => {
    // Mirrors the root CLAUDE.md API-compatibility rule and mobile's own
    // "render every inbox type, never silently drop a category" parity rule: a
    // type this build has never heard of must still parse.
    const future = {
      id: "inbox-5",
      recipient_type: "member",
      type: "some_future_type",
      details: { anything: "still a string" },
    };

    const parsed = InboxListSchema.safeParse([future]);
    expect(parsed.success).toBe(true);
  });
});
